/*
 * MulipleSelector.java
 *
 * Created on March 14, 2004, 7:22 PM
 */

package za.ac.up.cs.cirg.ciclops.client;

import java.util.Collection;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.LinkedList;

import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author  espeer
 */
public class MultipleSelector extends javax.swing.JDialog {
    
    /** Creates new form MulipleSelector */
    public MultipleSelector(java.awt.Frame parent, boolean modal, Collection selected, Collection unselected) {
        super(parent, modal);
        
        this.selected = selected;
        includedModel = new DefaultListModel();
        for (Iterator i = selected.iterator(); i.hasNext(); ) {
            Object tmp = i.next();
            includedModel.addElement(tmp);
            if (unselected.contains(tmp)) {
                unselected.remove(tmp);
            }
        }
        
        excludedModel = new DefaultListModel();
        for (Iterator i = unselected.iterator(); i.hasNext(); ) {
            excludedModel.addElement(i.next());
        }
        
        initComponents();
        
        included.getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        excluded.getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        included = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        left = new javax.swing.JButton();
        right = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        excluded = new javax.swing.JList();
        jPanel8 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setTitle("Selector");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel1.setText("Included:");
        jPanel3.add(jLabel1);

        jPanel2.add(jPanel3);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 400));
        included.setModel(includedModel);
        included.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                includedMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(included);

        jPanel2.add(jScrollPane1);

        jPanel6.add(jPanel2);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        left.setText("<<");
        left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftActionPerformed(evt);
            }
        });

        jPanel1.add(left);

        right.setText(">>");
        right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightActionPerformed(evt);
            }
        });

        jPanel1.add(right);

        jPanel6.add(jPanel1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 25));
        jLabel2.setText("Excluded:");
        jPanel5.add(jLabel2);

        jPanel4.add(jPanel5);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 400));
        excluded.setModel(excludedModel);
        excluded.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excludedMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(excluded);

        jPanel4.add(jScrollPane2);

        jPanel6.add(jPanel4);

        getContentPane().add(jPanel6);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 35));
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jPanel8.add(ok);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel8.add(cancel);

        getContentPane().add(jPanel8);

        pack();
    }//GEN-END:initComponents

    private void excludedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excludedMouseClicked
        if (evt.getClickCount() == 2) {
            int index = excluded.locationToIndex(evt.getPoint());
            includedModel.addElement(excludedModel.get(index));
            excludedModel.remove(index);
        }
    }//GEN-LAST:event_excludedMouseClicked

    private void includedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_includedMouseClicked
        if (evt.getClickCount() == 2) {
            int index = included.locationToIndex(evt.getPoint());
            excludedModel.addElement(includedModel.get(index));
            includedModel.remove(index);
        }
    }//GEN-LAST:event_includedMouseClicked

    private void rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightActionPerformed
        Object[] values = included.getSelectedValues();
        for (int i = 0; i < values.length; ++i) {
            excludedModel.addElement(values[i]);
            includedModel.removeElement(values[i]);
        }   
    }//GEN-LAST:event_rightActionPerformed

    private void leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftActionPerformed
        Object[] values = excluded.getSelectedValues();
        for (int i = 0; i < values.length; ++i) {
            includedModel.addElement(values[i]);
            excludedModel.removeElement(values[i]);
        }   
    }//GEN-LAST:event_leftActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        selected = new LinkedList();
        for (Enumeration e = includedModel.elements(); e.hasMoreElements(); ) {
            selected.add(e.nextElement());
        }
        closeDialog(null);
    }//GEN-LAST:event_okActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    public Collection getSelection() {
        return selected;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JList excluded;
    private javax.swing.JList included;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton left;
    private javax.swing.JButton ok;
    private javax.swing.JButton right;
    // End of variables declaration//GEN-END:variables
    
    private DefaultListModel includedModel;
    private DefaultListModel excludedModel;
    private Collection selected;
}
