/*
 * SimulationDialog.java
 *
 * Created on April 5, 2004, 11:32 AM
 */

package za.ac.up.cs.cirg.ciclops.client;

import java.awt.Frame;

import javax.swing.JOptionPane;

import za.ac.up.cs.cirg.ciclops.model.BrowserItem;
import za.ac.up.cs.cirg.ciclops.model.SimulationModel;
import za.ac.up.cs.cirg.ciclops.services.SimulationEditor;

/**
 *
 * @author  espeer
 */
public class SimulationDialog extends javax.swing.JDialog {
    
    /** Creates new form SimulationDialog */
    public SimulationDialog(java.awt.Frame parent, boolean modal, BrowserItem selected) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        
        try {
            editor = ServerContext.instance().getSimulationEditorHome().create();
            if (selected.getType() == BrowserItem.TYPE_CATEGORY) {
                model = new SimulationModel();
                model.setCategory(selected);
            }
            else {
                model = editor.getSimulation(selected.getId());
            }
        }
        catch (Exception ex) {
            throw new UnexpectedError(ex);
        }
        populateFormFromModel();
    }
    
    private void populateFormFromModel() {
    	id.setText(String.valueOf(model.getId()));
    	category.setText(model.getCategory().getPath());
    	name.setText(model.getName());
    	description.setText(model.getDescription());
    	configuration.setText(model.getConfiguration());
    	samples.setValue(new Integer(model.getNumberOfSamples()));
    }
    
    private void populateModelFromForm() {
    	model.setName(name.getText());
    	model.setConfiguration(configuration.getText());
    	model.setDescription(description.getText());
    	model.setNumberOfSamples(((Integer) samples.getValue()).intValue());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        selectCategory = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        edit = new javax.swing.JButton();
        samples = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        configuration = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        ok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        permissions = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Simulation");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 220, -1));

        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 20));

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jLabel6.setText("Category:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        category.setEditable(false);
        getContentPane().add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, -1));

        selectCategory.setText("...");
        selectCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCategoryActionPerformed(evt);
            }
        });

        getContentPane().add(selectCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 20, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Configuration"));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jPanel2.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jPanel2.add(samples, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 60, -1));

        jLabel3.setText("Samples:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 20));

        configuration.setEditable(false);
        jScrollPane2.setViewportView(configuration);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 590, 260));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(new javax.swing.border.TitledBorder("Description"));
        jScrollPane1.setViewportView(description);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 70));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 590, 100));

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        jLabel4.setText("Id:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 20));

        id.setEditable(false);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 80, -1));

        permissions.setText("Permissions");
        getContentPane().add(permissions, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        pack();
    }//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
    	if (JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this simulation?", "Delete Simulation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
    		try {
    			editor.deleteSimulation(model.getId());
    			closeDialog(null);
    		}
    		catch (Exception ex) {
    			throw new UnexpectedError(ex);
    		}
    	}
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    	ConfigBuilderDialog configBuilder = new ConfigBuilderDialog(parent, true, model.getConfiguration());
    	configBuilder.show();
    	model.setConfiguration(configBuilder.getConfiguration());
    	configuration.setText(model.getConfiguration());
    }//GEN-LAST:event_editActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        populateModelFromForm();
        try {
            editor.saveSimulation(model);
        }
        catch (Exception ex) {
            throw new UnexpectedError(ex);
        }
        finally {
        	closeDialog(null);
        }
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
    	closeDialog(null);
    }//GEN-LAST:event_cancelActionPerformed

    private void selectCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCategoryActionPerformed
       	BrowserDialog selector = new BrowserDialog(parent, true, BrowserItem.TYPE_CATEGORY);
    	selector.show();
    	BrowserItem item = selector.getSelected();
    	if (item != null) {
    		model.setCategory(item);
    		category.setText(item.getPath());
    	}
    }//GEN-LAST:event_selectCategoryActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField category;
    private javax.swing.JTextArea configuration;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea description;
    private javax.swing.JButton edit;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JButton ok;
    private javax.swing.JButton permissions;
    private javax.swing.JSpinner samples;
    private javax.swing.JButton selectCategory;
    // End of variables declaration//GEN-END:variables
    
    private SimulationEditor editor;
    private SimulationModel model;
    
    private Frame parent;
}
